#!/bin/bash
# KOPI AUTO UPGRADE BY NODDEX
if [[ $# -lt 1 ]]; then
    echo "ERROR: Enter new version | e.g. v14"
    exit
fi
GREEN="\e[1m\e[1;32m" # green color
RED="\e[1m\e[1;31m" # red color
BLUE='\033[0;34m'   # blue color
YELLOW="\e[1m\e[1;33m"  # yellow color
NC="\e[0m"          # no color
BINARY_VERSION=$1
DEST_HEIGHT=$2
BINARY_LINK="https://github.com/kopi-money/kopi/releases/download/$1/kopid-$1-linux-amd64"
RPC_PORT=$(grep -m 1 -oP '^laddr = "\K[^"]+' "$HOME/.kopid/config/config.toml" | cut -d ':' -f 3)
BINARY_LOCATION="$(which kopid)"
if command -v jq &> /dev/null; then
    echo "jq INSTALLED"
else
    echo "INSTALLING jq..."
    apt update && apt install jq -y
fi
a=`arch`
str="aarch"
result=$(echo $a | grep "${str}")
if [[ "$result" != "" ]]; then
        ARMCHECK=2;
else
        ARMCHECK=1;
fi
clear
echo -e "${RED}\n############################################\nKOPI UPGRADE BY NODDEX.COM\n############################################${NC}"
if [[ $ARMCHECK -eq 2 ]];then
  cd $HOME && rm kopi -r
  git clone https://github.com/kopi-money/kopi.git > /dev/null
  cd kopi
  git checkout $BINARY_VERSION
  make build
  echo -e "${YELLOW}\n############################################\nNEW VERSION IS READY FOR UPGRADE"
  /root/kopi/bin/kopid version
  echo -e "\n############################################${NC}"
  echo "Waiting 15s..."
  sleep 15
  if [  ! -z "$2" ]; then
    echo -e "${YELLOW}HEIGHT TO UPGRADE: $DEST_HEIGHT ${NC}"
    while :
      do
        CURRENT_HEIGHT=$(curl -s localhost:$RPC_PORT/status | jq -r .result.sync_info.latest_block_height)
        [[ $CURRENT_HEIGHT == $DEST_HEIGHT ]] && mv /root/kopi/bin/kopid $BINARY_LOCATION && systemctl restart kopid && echo -e "${GREEN}UPGRADE SUCCESSFULLY!!!${NC}" && break
        echo Block left: $((DEST_HEIGHT - CURRENT_HEIGHT))
        sleep 15
      done
  else
    mv /root/kopi/bin/kopid $BINARY_LOCATION && systemctl restart kopid && echo "UPGRADE SUCCESSFULLY!!!"
  fi
else
  wget -O kopid $BINARY_LINK > /dev/null
  chmod +x kopid
  echo -e "${YELLOW}\n############################################\nLOCATION FOUND: $BINARY_LOCATION \n\nOLD VERSION:"
  kopid version
  echo -e "\nNEW VERSION:"
  ./kopid version
  echo -e "############################################\n ${NC}"
  echo "Waiting 15s..."
  sleep 15
  if [ ! -z "$2" ]; then
    echo -e "${YELLOW}HEIGHT TO UPGRADE: $DEST_HEIGHT ${NC}"
    while :
    do
      CURRENT_HEIGHT=$(curl -s localhost:$RPC_PORT/status | jq -r .result.sync_info.latest_block_height)
      [[ $CURRENT_HEIGHT == $DEST_HEIGHT ]] && mv kopid $BINARY_LOCATION && systemctl restart kopid && echo "UPGRADE SUCCESSFULLY!!!" && break
      echo Block left: $((DEST_HEIGHT - CURRENT_HEIGHT))
      sleep 15
    done
  else
    mv kopid $BINARY_LOCATION && systemctl restart kopid && echo "UPGRADE SUCCESSFULLY!!!"
  fi
fi
